#!/usr/bin/env sh

if [ -z "$PREFIX" ]; then
	if [ "$(id -u)" = 0 ]; then
		PREFIX=/usr/local
	else
		PREFIX="$HOME/.local"
	fi
fi

if [ -z "$FIXCOLS_SO" ]; then
	FIXCOLS_SO="$PREFIX/lib/fixcols.so"
fi

if [ ! -e "$FIXCOLS_SO" ]; then
	echo "fixcols: ERROR: fixcols library does not exist: $FIXCOLS_SO" 1>&2
	exit 1
fi

LD_PRELOAD="$FIXCOLS_SO" "$@"
