.\"
.Dd May 04, 2020
.Os
.Dt FIXWINSZ 1
.IX Title "FIXWINSZ 1"
.TH FIXWINSZ 1 "2020-05-04" "fixwinsz 0.10" "Restrict terminal size assumed by programs"

.SH "NAME"
.IX Header "NAME"
.Nm fixwinsz
.Nd restrict terminal size assumed by programs

.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.B "fixwinsz"
\fIWIDTH\fR[\fBx\fR\fIHEIGHT\fR] [\fB--\fR] \fICOMMAND\fR [\fIARGS\fR]...

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
.IR fixwinsz (1)
is a
.IR pty (7)
wrapper which limits the child terminal size to \fIWIDTH\fRx\fIHEIGHT\fR.
If \fIHEIGHT\fR has not been specified, it is kept unchanged.  \fIWIDTH\fR is
required.

.SH "BUGS"
.IX Header "BUGS"
.nr step 1 1
.IP \n[step] 4
Does not emulate the DECSTBM\fI[1][2]\fR ANSI control code.
Programs that rely on it, e.g.
.IR less (1),
will mangle the output.

.SH "REFERENCES"
.TP
[1]
.I https://vt100.net/docs/vt510-rm/DECSTBM.html

.TP
[2]
\(lqchange_scroll_region\(rq in
.IR terminfo (5)

.SH "SEE ALSO"
.IX Header "SEE ALSO"
.IR forkpty (3)
