.Dd June 11, 2021
.Os Linux
.Dt FIXWINSZ 1 IND


.Sh NAME
.Nm fixwinsz
.Nd launch command in a resized PTY


.Sh SYNOPSIS
.Nm fixwinsz
.Op Ar OPTIONS Ns Li ...
.Ar WIDTH Ns Oo x Ns Ar HEIGHT Oc
.Oo Fl - Oc
.Ar COMMAND Ns Li ...


.Sh DESCRIPTION
.Xr fixwinsz 1
is a
.Xr pty 7
wrapper which limits the child terminal size to
.Ar WIDTH Ns x Ns Ar HEIGHT .
If
.Ar HEIGHT
has not been specified, height of the parent terminal is used.
.Ar WIDTH
is required.


.Sh OPTIONS
.Bl -tag "-----" -compact
.It Fl W
If
.Ar HEIGHT
is not specified, ignore
.Em SIGWINCH
so that
.Ar COMMAND
is launched with the height of the parent terminal and stays that way. By
default, window height changes are propagated via
.Em SIGWINCH .

.Sm off
.It Fl -stderr= Sy PTY | Sy FIFO | Sy MUX | Sy DETECT | Sy DISCARD Ns \~ \~ (default: \~ Sy DETECT )
.Sm on
Choose how to handle
.Sy COMMAND Ns 's
standard error output:

.Bl -tag -width "DISCARD" -compact -offset indent
.It Sy PTY
Open a separate pty for stderr.  This is intended for programs that use stderr
for error reporting and determine whether to use colors with, e.g.
.Xr isatty 3 .
However, by convention, stdout and stderr usually refer to the same (controlling)
terminal, so not all programs may work correctly.
.Pp
.It Sy FIFO
Open a FIFO for stderr.
.Pp
.It Sy MUX
Bind stderr to the controlling terminal. In the parent
.Xr fixwinsz 1
process, stderr will be (irreversibly) mixed with stdout.
.Pp
.It Sy DETECT
If stderr of the parent
.Xr fixwinsz 1
process is a tty, handle stderr as
.Sy PTY ,
and as
.Sy FIFO
otherwise.
.Pp
.It Sy DISCARD
Open a non-tty descriptor for child stderr and discard its output.
.El
.El
.Pp
Note that currently, stdin and stdout always behave as if they were
.Sy DETECT ,
with the caveat that they share
.Sy COMMAND Ns 's
controlling terminal.


.Sh BUGS
.Bl -enum -compact
.It
Does not emulate the DECSTBM
.Em [1][2]
ANSI control code. Programs that rely on it, e.g.
.Xr less 1 ,
will mangle the output and leave the terminal with incorrect margins.
.El


.Sh REFERENCES
.Bl -tag -width "[1]" -compact
.It Em [1]
.Lk https://vt100.net/docs/vt510-rm/DECSTBM.html "DECSTBM"
.It Em [2]
.Ql change_scroll_region
in
.Xr terminfo(5)
.El


.Sh SEE ALSO
.Xr forkpty 3
