.\"
.Dd August 10, 2018
.Os
.Dt FIXWINSZ 1
.IX Title "FIXWINSZ 1"
.TH FIXWINSZ 1 "2019-08-10" "fixwinsz 0.07" "Restrict terminal size assumed by programs"

.SH "NAME"
.IX Header "NAME"
.Nm fixwinsz
.Nd restrict terminal size assumed by programs

.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.B "fixwinsz"
\fIWIDTH\fR[\fBx\fR\fIHEIGHT\fR] \fICOMMAND\fR [\fIARGS\fR]...

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
.IR fixwinsz (1)
is an LD_PRELOAD wrapper which intercepts the
.BR TIOCGWINSZ
.IR ioctl (2),
which is the method that Linux programs use to get the size of the parent
terminal, and limits the returned area size to \fIWIDTH\fRx\fIHEIGHT\fR.
(If \fIHEIGHT\fR has not been specified, it is kept unchanged.  \fIWIDTH\fR
is required.)

.SH RATIONALE
.IX Header "RATIONALE"
.IR fixwinsz (1)
was created to non-invasively force
.IR wget (1)'s
progress bar to stay limited to a reasonable size, thus avoiding the problem
of garbage symbols all over the place any time the terminal would get resized.

.SH SEE ALSO
.IX Header "SEE ALSO"
.IR ld.so (8),
.IR dlsym (3),
.IR ioctl (2),
.IR ioctl_tty (2),
.IR ncurses (3NCURSES)
